export type ReadingItem = {
  id: string;
  level: 1 | 2 | 3;
  title: string;
  titleZh: string;
  text: string;
  translation: string;
  focus: string[];
};

export type ReadingQuestion = {
  question: string;
  options: [string, string, string];
  answer: number;
  explanation: string;
};

export const readings: ReadingItem[] = [
  { id: "r1", level: 1, title: "A Good Morning", titleZh: "美好的早晨", text: "I wake up at seven every morning. First, I open the window and look at the sky. The air is cool and fresh. I drink a glass of water and eat an apple with some bread. Then I wash my face and put on my clothes. My bag is near the door. I check my phone, take my bag, and smile. I am ready for a new day.", translation: "我每天早上七点醒来。首先，我打开窗户，看看天空。空气凉爽又清新。我喝一杯水，吃一个苹果和一些面包。然后我洗脸并穿好衣服。我的包在门旁边。我查看手机，拿起包，笑了笑。我已经准备好迎接新的一天。", focus: ["wake", "water", "ready"] },
  { id: "r2", level: 1, title: "At the Café", titleZh: "在咖啡馆", text: "I go to a small café after work. A server shows me to a table near the window. I sit down and look at the menu. I order a hot coffee without sugar and a piece of cake. The coffee smells good, and the cake is soft and sweet. I read a short message on my phone. Before I leave, I say thank you to the server and pay the bill.", translation: "下班后，我去一家小咖啡馆。一位服务员带我到窗边的一张桌子旁。我坐下来看菜单。我点了一杯不加糖的热咖啡和一块蛋糕。咖啡闻起来很香，蛋糕柔软又香甜。我在手机上读了一条短消息。离开前，我向服务员道谢并结账。", focus: ["table", "order", "without"] },
  { id: "r7", level: 1, title: "A Quiet Home", titleZh: "安静的家", text: "My home is small, but I like it very much. The living room has one table, two chairs, and a green plant. I clean the room every Saturday. In the afternoon, I open the window and make some tea. Then I sit in my favorite chair with a book. The street outside is busy, but my room is quiet. I read for an hour and feel calm and happy.", translation: "我的家很小，但我非常喜欢它。客厅里有一张桌子、两把椅子和一盆绿色植物。我每周六打扫房间。下午，我打开窗户，泡一些茶。然后我拿着一本书，坐在最喜欢的椅子上。外面的街道很繁忙，但我的房间很安静。我读一个小时的书，感到平静而快乐。", focus: ["home", "room", "book"] },
  { id: "r8", level: 1, title: "My Friend", titleZh: "我的朋友", text: "My good friend is called Anna. She works in a shop near my office. We meet after work on Friday. Sometimes we drink tea and talk about our week. Sometimes we walk in the park and take photos of flowers. Anna is kind and funny. She listens when I have a problem, and I help her too. At the end of the evening, we make a plan for our next meeting.", translation: "我的好朋友叫安娜。她在我办公室附近的一家商店工作。我们周五下班后见面。有时我们喝茶，聊聊这一周；有时我们在公园散步，拍花的照片。安娜善良又风趣。当我遇到问题时，她会倾听，我也会帮助她。那天晚上分别前，我们会计划下一次见面。", focus: ["friend", "talk", "park"] },
  { id: "r9", level: 1, title: "A Blue Shirt", titleZh: "一件蓝色衬衫", text: "I need a new shirt for a family dinner. In the shop, I find a blue one that looks nice. I try it on, but it is too small. I ask the shop worker for a larger size. She brings another shirt, and this one fits well. I look in the mirror and smile. The price is good, so I buy it. I keep the receipt in my bag and go home.", translation: "我需要一件新衬衫去参加家庭晚餐。在商店里，我找到一件很好看的蓝色衬衫。我试穿了一下，但它太小了。我请店员拿一件尺码大一点的。她带来另一件，这次很合身。我照照镜子，笑了。价格也合适，所以我买下它，把小票放进包里，然后回家。", focus: ["need", "shirt", "size"] },
  { id: "r3", level: 2, title: "A Delayed Flight", titleZh: "延误的航班", text: "Mia arrives at the airport two hours before her flight. She checks in, shows her passport, and leaves her large bag at the desk. Then she walks to Gate 18 and buys a bottle of water.\n\nWhen Mia looks at the screen, she sees that her flight has been delayed by ninety minutes. At first, she feels worried because a friend is waiting for her in another city. She sends a message to explain the delay. Her friend replies, “No problem. Take your time.”\n\nMia finds a quiet seat near the gate and reads a book. Later, an airport worker announces that boarding will begin soon. Mia puts her book away, checks her boarding pass, and joins the line. The wait was long, but she stayed calm and used the time well.", translation: "米娅在航班起飞前两小时到达机场。她办理值机，出示护照，并把大行李留在柜台托运。然后她走到18号登机口，买了一瓶水。\n\n当米娅查看屏幕时，她发现航班延误了九十分钟。起初她有些担心，因为一位朋友正在另一座城市等她。她发消息说明延误情况。朋友回复：“没关系，慢慢来。”\n\n米娅在登机口附近找到一个安静的座位看书。后来，机场工作人员广播说很快就要开始登机。米娅收起书，检查登机牌，然后加入队伍。等待虽然很久，但她保持平静，也很好地利用了时间。", focus: ["arrive", "delayed", "boarding"] },
  { id: "r4", level: 2, title: "The Right Room", titleZh: "合适的房间", text: "Leo reaches his hotel after a long train journey. At the front desk, he gives his name and says that he has a reservation for three nights. The receptionist finds his booking and asks for his passport.\n\nLeo explains that he needs a quiet room because he has an online meeting early the next morning. His first room is close to the lift, and he can hear people talking outside. He returns to the front desk and politely asks if another room is available.\n\nThe receptionist gives him a room at the end of the hall. It is bright, clean, and very quiet. Breakfast is also included in the price. Leo puts his bag beside the bed, takes a shower, and prepares for his meeting. He is pleased that he asked for the room he needed.", translation: "经过漫长的火车旅程，利奥到达酒店。他在前台报上姓名，并说自己预订了三晚。接待员找到订单，请他出示护照。\n\n利奥解释说，他第二天一早有线上会议，所以需要一间安静的房间。他拿到的第一间房靠近电梯，可以听到外面的人说话。他回到前台，礼貌地询问是否还有其他房间。\n\n接待员给了他走廊尽头的一间房。那里明亮、干净，而且非常安静。房价还包含早餐。利奥把包放在床边，洗了个澡，然后为会议做准备。他很庆幸自己提出了真正需要的房间。", focus: ["reservation", "quiet", "available"] },
  { id: "r10", level: 2, title: "Lunch for Two", titleZh: "两个人的午餐", text: "Emma meets her old friend David for lunch at a new restaurant. They have not seen each other for six months, so they have a lot to talk about. A server brings the menu and a bottle of water.\n\nDavid wants fish, but he is not sure which dish to choose. He asks the server for a recommendation. Emma orders chicken with rice, and David chooses the fish with vegetables. They decide to share a salad.\n\nWhile they eat, they talk about work, family, and a trip they hope to take together. The food is fresh and delicious, and the service is friendly. After the meal, Emma asks for the bill. David wants to pay, but Emma suggests that they share the cost. They leave the restaurant smiling and plan to meet again next month.", translation: "艾玛在一家新餐厅和老朋友戴维见面吃午餐。他们已经六个月没见，因此有很多话要聊。服务员拿来菜单和一瓶水。\n\n戴维想吃鱼，但不确定该选哪道菜。他请服务员推荐。艾玛点了鸡肉配米饭，戴维选择了鱼配蔬菜。他们还决定一起分享一份沙拉。\n\n吃饭时，他们聊工作、家人，以及一次希望共同完成的旅行。食物新鲜美味，服务也很友好。饭后，艾玛请服务员拿账单。戴维想付款，但艾玛建议两人平摊。他们微笑着离开餐厅，并计划下个月再次见面。", focus: ["lunch", "order", "bill"] },
  { id: "r11", level: 2, title: "The Last Bus", titleZh: "末班公交车", text: "Kai leaves work later than usual on Friday evening. It is raining, and the streets are busy. He walks quickly to the bus station because the last bus home leaves at ten o’clock.\n\nWhen he arrives, the station is almost empty. Kai looks at the time and realizes that he is five minutes late. The last bus has already gone. He checks a taxi app, but the price is very high because of the rain.\n\nKai calls his friend Ben and explains the problem. Ben is still nearby and offers to drive him home. While Kai waits, he buys a hot drink from a small shop. Twenty minutes later, Ben arrives. Kai thanks him and promises to buy dinner next time. A difficult evening becomes much easier because a friend is ready to help.", translation: "周五晚上，凯比平时更晚下班。天正在下雨，街道也很拥挤。他快步走向公交车站，因为回家的末班车十点发车。\n\n到达时，车站几乎没人了。凯看了看时间，发现自己晚了五分钟。末班车已经开走了。他查看打车软件，但因为下雨，价格非常高。\n\n凯给朋友本打电话，说明了情况。本还在附近，主动提出开车送他回家。等待时，凯在小店买了一杯热饮。二十分钟后，本到了。凯向他道谢，并答应下次请他吃饭。因为朋友愿意帮忙，一个麻烦的夜晚变得轻松多了。", focus: ["station", "taxi", "help"] },
  { id: "r12", level: 2, title: "Hotel Morning", titleZh: "酒店的早晨", text: "Sara wakes up early on the final day of her holiday. Sunlight comes through the hotel window, and the city is already busy below. She takes a shower, gets dressed, and checks that everything is in her suitcase.\n\nBreakfast is served downstairs until nine thirty. Sara chooses bread, fruit, and a cup of coffee. She sits near the window and writes a short list of places she enjoyed visiting during the trip.\n\nBefore leaving, Sara returns to her room one last time. She checks the bathroom, looks under the bed, and finds a phone charger beside the table. At the front desk, she gives the room key to a member of staff and asks for a taxi to the station. The taxi arrives in ten minutes. Sara leaves the hotel with her suitcase, her charger, and many good memories.", translation: "假期的最后一天，萨拉很早就醒了。阳光透过酒店窗户照进来，楼下的城市已经开始忙碌。她洗澡、穿衣，并检查所有东西是否都放进了行李箱。\n\n早餐供应到九点半。萨拉选了面包、水果和一杯咖啡。她坐在窗边，写下一份简短清单，记录旅途中自己喜欢去的地方。\n\n离开前，萨拉最后一次回到房间。她检查浴室，看看床底，并在桌旁发现了手机充电器。在前台，她把房卡交给工作人员，并请对方叫一辆去车站的出租车。十分钟后车到了。萨拉带着行李箱、充电器和许多美好回忆离开酒店。", focus: ["shower", "breakfast", "key"] },
  { id: "r5", level: 3, title: "Choosing Carefully", titleZh: "谨慎选择", text: "Nora needs a warm jacket for a winter trip. She has seen many jackets online, but she wants to try one on before paying. On Saturday morning, she visits a large clothing store in the city center.\n\nThe first jacket she likes is dark green and feels very warm. However, when Nora checks the price, she discovers that it costs much more than she planned to spend. A shop assistant notices her hesitation and asks if she needs help. Nora explains her budget and says that she would prefer a simple jacket without a large brand name.\n\nThe assistant brings two cheaper choices. The first is the right price, but its sleeves are too short. The second comes in a larger size and has useful inside pockets. Nora tries it on and walks around the store. It fits well, feels comfortable, and is light enough to carry during travel.\n\nBefore buying it, Nora checks the washing instructions and asks about the return policy. The assistant says she can return it within thirty days if she keeps the receipt. Nora pays by credit card and puts the receipt safely in her wallet. She leaves feeling confident because she compared price, comfort, and quality instead of choosing too quickly. The jacket is not the most fashionable one in the store, but it is the best choice for her needs.", translation: "诺拉需要一件保暖夹克，准备冬季旅行时穿。她在网上看过很多款式，但付款前还是想亲自试穿。周六早上，她来到市中心的一家大型服装店。\n\n她喜欢的第一件夹克是深绿色的，摸起来很暖和。然而，看到价格后，她发现它远远超出了预算。店员注意到她在犹豫，便询问是否需要帮助。诺拉说明了自己的预算，并表示更喜欢没有醒目品牌标志的简洁夹克。\n\n店员拿来两件更便宜的。第一件价格合适，但袖子太短；第二件有更大的尺码，还有实用的内袋。诺拉试穿后在店里走了走。它很合身、很舒适，也足够轻便，旅行时容易携带。\n\n购买前，诺拉查看了洗涤说明，并询问退货规定。店员说，只要保留小票，三十天内可以退货。诺拉用信用卡付款，把小票安全地放进钱包。她离开时很有信心，因为自己比较了价格、舒适度和质量，而不是仓促决定。这件夹克不是店里最时髦的一件，却最符合她的实际需要。", focus: ["price", "return", "receipt"] },
  { id: "r6", level: 3, title: "A Friendly Conversation", titleZh: "一次友好的交谈", text: "Daniel is walking to the library when a visitor stops him near the train station. She holds a map and looks worried. Speaking carefully in English, she asks how to get to the city museum. Daniel knows the area well, so he begins to explain the route.\n\nHe tells her to walk along King Street, turn left after the bank, and take Bus 2. Although Daniel speaks slowly, the visitor does not understand the name of the bus stop. She looks embarrassed and says, “Sorry, could you repeat that?” Daniel repeats the sentence, but the unfamiliar street names are still difficult for her.\n\nInstead of speaking louder, Daniel tries a simpler way. He points to the map, marks the correct bus stop, and writes the bus number on a small piece of paper. Then he shows her a photo of the museum entrance on his phone. The visitor smiles because the directions are finally clear.\n\nThey walk together to the bus stop. While they wait, the visitor says she is from Brazil and is spending a week in the city. Daniel tells her about a park behind the museum that many tourists miss. When the bus arrives, she thanks him warmly. Daniel continues to the library, pleased that patience and simple language turned a difficult conversation into a friendly one.", translation: "丹尼尔正走向图书馆，一位游客在火车站附近叫住了他。她拿着地图，看起来很担心。她认真地用英语询问怎样去市博物馆。丹尼尔很熟悉这个地区，于是开始说明路线。\n\n他告诉她沿国王街前行，在银行后左转，再乘2路公交车。虽然丹尼尔说得很慢，游客仍没听懂公交站的名字。她有些不好意思地说：“抱歉，可以再说一遍吗？”丹尼尔重复了那句话，但陌生的街名对她来说仍然很难。\n\n丹尼尔没有提高音量，而是换了一种更简单的方式。他指着地图，标出正确的公交站，并把公交车号码写在一张小纸片上。然后，他用手机给她看博物馆入口的照片。游客笑了，因为路线终于清楚了。\n\n他们一起走到公交站。等车时，游客说她来自巴西，要在这座城市停留一周。丹尼尔告诉她，博物馆后面有一座许多游客会错过的公园。公交车到站后，她热情地向他道谢。丹尼尔继续前往图书馆，很高兴耐心和简单的语言把一次困难的交流变成了友好的相遇。", focus: ["understand", "repeat", "explain"] },
  { id: "r13", level: 3, title: "A Helpful Message", titleZh: "一条有用的消息", text: "Ben is traveling across town for an important team meeting. He leaves home early because the journey usually takes forty minutes. Halfway there, his phone shows a new message from his manager: a water leak has closed their office building for the morning. The meeting will take place at a shared workspace on another street.\n\nAt first, Ben feels confused. The message names the new building, but he has never visited it. He opens a map and sees that it is in the opposite direction. If he continues on the same bus, he will be late. He gets off at the next stop and studies the travel choices. A train is fastest, but the station is ten minutes away on foot.\n\nBen replies to his manager to confirm that he has read the update. He also sends a short message to two coworkers who may not have checked their phones. Then he walks quickly to the station, buys a ticket, and takes the next train. During the journey, he reviews the meeting schedule and organizes his notes.\n\nBen reaches the new building five minutes before the meeting. One coworker thanks him for forwarding the change because she almost went to the closed office. Their manager begins by explaining the new plan for the day. Ben realizes that a helpful message should be clear, timely, and easy to act on. His manager’s update gave the address and reason; Ben’s quick reply and follow-up helped the rest of the team arrive safely.", translation: "本正在穿过城市去参加一次重要的团队会议。他很早离开家，因为路程通常需要四十分钟。走到一半时，手机收到经理的新消息：办公室大楼早上因漏水问题关闭，会议将改在另一条街的共享办公空间举行。\n\n起初，本有些困惑。消息写了新大楼的名字，但他从没去过。他打开地图，发现那里在相反方向。如果继续坐同一班公交车，他就会迟到。他在下一站下车，查看不同的出行方案。乘火车最快，但步行到车站需要十分钟。\n\n本回复经理，确认自己已看到更新。他还给两位可能没看手机的同事发了简短消息。随后，他快步走到车站，买票并坐上下一班火车。途中，他查看会议日程，整理自己的笔记。\n\n本在会议开始前五分钟到达新大楼。一位同事感谢他转发变更消息，因为她差点去了已经关闭的办公室。经理先说明当天的新安排。本意识到，一条有用的消息应该清楚、及时，而且让人容易采取行动。经理的更新提供了地址和原因；本迅速回复并提醒同事，也帮助团队其他人安全到达。", focus: ["message", "schedule", "reply"] },
  { id: "r14", level: 3, title: "A New Neighborhood", titleZh: "新的社区", text: "After moving to a new neighborhood, Lina needs to learn where to buy food, catch a bus, and spend time outdoors. During her first week, she walks around each evening and saves useful places on her phone. She soon finds two markets, but they offer very different experiences.\n\nThe first market is large and modern. It has a wide choice of fruit, vegetables, and food from other countries. Its prices are lower, and it stays open until midnight. However, it is nearly two kilometers from Lina’s apartment. She must take a bus, and the return journey can be slow when the roads are busy.\n\nThe second market is only five minutes away on foot. It is smaller, and some products cost a little more. Still, the owner remembers customers and often recommends fresh local food. There is a bus stop outside, a pharmacy next door, and a quiet park across the street. Lina can complete several tasks in one short trip.\n\nAt first, Lina thinks the large market is clearly better because saving money matters. After two rainy evenings and one crowded bus ride, she changes her mind. She decides to use the nearby market for everyday shopping and visit the larger one once a month for special items.\n\nThis simple comparison teaches Lina something about her new life. The cheapest choice is not always the best choice. Time, transport, comfort, and friendly service also have value. By understanding what she needs most often, she creates a routine that is both practical and pleasant.", translation: "搬到新社区后，莉娜需要了解去哪里买食物、乘公交车和进行户外活动。第一周里，她每天傍晚四处走走，并把有用的地点保存在手机上。她很快发现了两个市场，但两者提供的体验非常不同。\n\n第一个市场又大又现代，水果、蔬菜和外国食品的选择很多。价格更低，营业到午夜。不过，它离莉娜的公寓将近两公里。她必须乘公交车，路上拥堵时返程会很慢。\n\n第二个市场步行只需五分钟。它比较小，有些商品也稍贵一些。不过，店主能记住顾客，还经常推荐新鲜的本地食物。门外有公交站，隔壁有药房，街对面还有一座安静的公园。莉娜短短一次出门就能完成好几件事。\n\n起初，莉娜认为大市场显然更好，因为省钱很重要。经历两个雨夜和一次拥挤的公交行程后，她改变了想法。她决定日常购物去附近的市场，每月再去一次大市场购买特别的东西。\n\n这个简单的比较让莉娜更了解自己的新生活。最便宜的选择并不总是最好的。时间、交通、舒适度和友好的服务同样有价值。弄清自己最常需要什么后，她建立了一套实用又愉快的生活习惯。", focus: ["routine", "market", "transport"] },
  { id: "r15", level: 3, title: "The Wrong Size", titleZh: "不合适的尺码", text: "Jin orders a pair of running shoes from an online store. He reads the size guide, measures his feet, and chooses carefully. Three days later, a package arrives. The shoes look exactly like the photos, but when Jin tries them on, they feel much too tight. He checks the label and discovers that the store sent the wrong size.\n\nJin needs the shoes for a weekend race, so he contacts customer service immediately. Instead of writing only “My order is wrong,” he includes the order number, the size he requested, and the size he received. He also takes a clear photo of the label and keeps the receipt and package.\n\nA customer service representative named Rosa replies within an hour. She apologizes for the mistake and offers two choices: Jin can receive a full refund, or the store can send the correct size by fast delivery. Jin still wants the shoes, so he asks for a replacement. He also explains that he needs them before the race.\n\nRosa checks the local store and finds the correct pair. A driver delivers it the next afternoon and collects the first package. Jin tries on the new shoes and walks around his apartment. This time, they fit perfectly. He sends Rosa a short thank-you message.\n\nThe problem is solved quickly because both people communicate clearly. Jin provides complete information without becoming angry, and Rosa listens, explains the choices, and takes action. A wrong order is inconvenient, but good customer service can turn it into a positive experience.", translation: "金从一家网店订购了一双跑鞋。他阅读尺码表，测量双脚，认真做出选择。三天后，包裹到了。鞋子看起来和照片完全一样，但金试穿后觉得太紧了。他检查标签，发现商店发错了尺码。\n\n金周末比赛要穿这双鞋，所以立刻联系客服。他没有只写“我的订单错了”，而是提供了订单号、自己下单的尺码和实际收到的尺码。他还拍下清晰的标签照片，并保留小票和包装。\n\n一位名叫罗莎的客服人员在一小时内回复。她为错误道歉，并给出两个选择：全额退款，或者通过快速配送寄出正确尺码。金仍然想要这双鞋，所以选择换货，并说明比赛前就需要这双鞋。\n\n罗莎查询本地门店，找到了正确的鞋。第二天下午，司机送来新鞋，同时取走第一件包裹。金试穿后在公寓里走了走，这次完全合脚。他给罗莎发了一条简短的感谢消息。\n\n问题能迅速解决，是因为双方沟通清楚。金提供了完整信息，没有发火；罗莎认真倾听，解释选择并采取行动。发错订单确实不方便，但良好的客户服务可以把它变成一次积极的体验。", focus: ["customer", "receipt", "service"] },
];

export const readingQuestions: Record<string, ReadingQuestion> = {
  r1: { question: "作者紧接着拿起包之前做了什么？", options: ["喝了一杯水", "查看了手机", "关上了窗户"], answer: 1, explanation: "正文最后写道，作者先查看手机，然后拿起门边的包。" },
  r2: { question: "作者点的咖啡有什么特点？", options: ["是热咖啡，而且不加糖", "是冰咖啡，而且加牛奶", "是甜咖啡，而且不配蛋糕"], answer: 0, explanation: "作者点了一杯不加糖的热咖啡，并另外点了一块蛋糕。" },
  r3: { question: "米娅得知航班延误后，起初为什么担心？", options: ["她找不到 18 号登机口", "她把护照忘在了值机柜台", "有一位朋友正在另一座城市等她"], answer: 2, explanation: "正文明确说明，她担心是因为朋友正在另一座城市等候。" },
  r4: { question: "利奥为什么要求更换第一间客房？", options: ["房间没有包含早餐", "房间靠近电梯，外面的谈话声会影响早晨的会议", "房间离前台太远，不方便退房"], answer: 1, explanation: "利奥第二天一早有线上会议，而第一间房靠近电梯，能听见外面的人说话。" },
  r5: { question: "诺拉最终选择第二件便宜夹克，最主要的原因是什么？", options: ["它兼顾了预算、合身度、舒适度和旅行实用性", "它是店里最时髦、品牌标志最大的一件", "它可以在不保留小票的情况下随时退货"], answer: 0, explanation: "第二件夹克尺码合适、穿着舒适、便于携带且有内袋，也没有超出她的预算。" },
  r6: { question: "重复口头路线仍无效后，丹尼尔怎样让游客最终听懂了？", options: ["他提高音量，一遍遍重复陌生的街名", "他让游客独自乘车，再向司机询问", "他结合地图标记、书面车号和入口照片来说明"], answer: 2, explanation: "丹尼尔改用地图、写下的公交车号和手机照片，把抽象的口头说明变得直观。" },
  r7: { question: "作者每周六会做什么？", options: ["打扫房间", "给绿色植物买新花盆", "去繁忙的街上读书"], answer: 0, explanation: "正文直接写道，作者每周六打扫房间。" },
  r8: { question: "安娜和作者在晚上分别前会做什么？", options: ["互相赠送一张花的照片", "计划下一次见面的安排", "一起去安娜工作的商店"], answer: 1, explanation: "正文结尾说明，两人会在那天晚上分别前计划下一次见面。" },
  r9: { question: "作者为什么没有买最先试穿的蓝色衬衫？", options: ["它的价格太高", "它不是作者想要的颜色", "它的尺码太小"], answer: 2, explanation: "第一件蓝色衬衫很好看，但作者试穿后发现它太小了。" },
  r10: { question: "艾玛和戴维最后怎样处理午餐费用？", options: ["由戴维支付全部费用", "按照艾玛的建议共同分担", "由餐厅免去这顿饭的费用"], answer: 1, explanation: "戴维原本想付款，但艾玛建议两人平摊费用。" },
  r11: { question: "是什么让凯这个麻烦的夜晚变得容易起来？", options: ["本主动开车送他回家", "出租车平台降低了雨天价格", "末班公交车返回车站接他"], answer: 0, explanation: "凯错过末班车且出租车很贵，本及时提出开车送他回家。" },
  r12: { question: "萨拉最后一次检查房间时找到了什么？", options: ["遗落在床下的房卡", "放在浴室里的旅行清单", "放在桌旁的手机充电器"], answer: 2, explanation: "她检查浴室和床下后，在桌旁发现了手机充电器。" },
  r13: { question: "哪一项最能体现文中所说的消息“清楚、及时、容易采取行动”？", options: ["本等到原办公室后才询问会议是否改变", "经理说明新地点和原因，本随即确认、提醒同事并改变路线", "经理只说会议有变化，本让同事自行寻找地址"], answer: 1, explanation: "经理提供了采取行动所需的信息，本又迅速确认、转告并调整交通方案。" },
  r14: { question: "莉娜最终形成的购物安排体现了怎样的权衡？", options: ["日常选择省时便利的近处市场，特殊采购再去价格较低的大市场", "完全放弃价格较低的大市场，只考虑店主是否友好", "每天去大市场省钱，下雨时才偶尔使用近处市场"], answer: 0, explanation: "她把近处市场的便利用于日常购物，同时每月去大市场购买特别商品，兼顾了多种需要。" },
  r15: { question: "这次尺码问题能够迅速解决，最关键的共同原因是什么？", options: ["金表现得很生气，迫使商店立即退款", "跑鞋照片与实物完全一样，所以尺码问题并不重要", "金提供完整证据，罗莎明确给出选择并迅速采取行动"], answer: 2, explanation: "金清楚提供订单、尺码和照片，罗莎则及时回应、说明方案并落实换货。" },
};
