import { CONTENT_REVISION, fetchJsonWithRecovery } from "./content-loader";

export type SentenceBand = "short" | "medium" | "long";
export type SentenceItem = {
  id: number;
  sourceId: number;
  translationId: number;
  text: string;
  translation: string;
  author: string;
  translationAuthor: string;
  length: SentenceBand;
  category: "daily" | "social" | "food" | "travel" | "shopping" | "work" | "help";
  adapted?: boolean;
};

const SENTENCE_CORRECTIONS: Record<number, Partial<Pick<SentenceItem, "text" | "translation" | "category">>> = {
  8: { translation: "能和你谈一会儿吗？" },
  74: { category: "food" },
  98: { text: "How late can we use this?", translation: "我们最晚可以用到什么时候？" },
  115: { translation: "我们怎样才能将它付诸实践？" },
  125: { translation: "请把门开着，好吗？" },
  239: { translation: "我能把那件事办成。" },
  258: { translation: "我们可以一起走过去。" },
  523: { text: "I care about you very much.", translation: "我很在乎你。", category: "social" },
  458: { text: "Come whenever you are ready!", translation: "你准备好时就来吧！" },
  557: { text: "Have a safe and pleasant trip.", translation: "祝你旅途平安愉快。", category: "travel" },
  993: { text: "We work well together!", translation: "我们合作得很好！", category: "work" },
  853: { text: "Do you have a health problem?", translation: "你有健康方面的问题吗？" },
  987: { translation: "多喝点水！" },
  988: { text: "I study English every evening.", translation: "我每天晚上学英语。" },
  1005: { translation: "每当我听到这首歌，就会想起你、思念你。" },
  1022: { text: "I would like to discuss the price with you." },
  1026: { category: "social" },
  1045: { text: "May I ask whether I can open a bank account here?", translation: "请问我可以在这里开银行账户吗？" },
  1051: { category: "social" },
  1054: { translation: "请别让门一直开着，好吗？" },
  1057: { translation: "你必须特别注意自己的饮食。" },
  1083: { text: "Start with small goals, then aim higher as you improve.", translation: "先设定小目标，进步后再提高目标。" },
  1093: { category: "travel" },
  1094: { text: "On a bus, I always choose a seat near the front.", translation: "坐公交车时，我总会选靠前的座位。" },
  1103: { text: "I wonder if you have something I can write with.", translation: "我想知道你有没有笔可以写。" },
  1163: { text: "I will provide you with all the necessary information.", translation: "我会向你提供所有必要的信息。" },
  1198: { translation: "我也很想去看看。" },
  1220: { text: "I promise that I will send you the details.", translation: "我保证会把详细信息发给你。", category: "work" },
  1298: { translation: "我们一起去图书馆学习，怎么样？" },
  1414: { text: "Do you know of a cheap hotel near here?", translation: "你知道这附近有便宜的酒店吗？", category: "travel" },
  1416: { translation: "你喜欢喝哪一种酒？", category: "food" },
  1447: { translation: "我做梦也没想到会在这里碰到你。" },
  1600: { translation: "我想让你教我怎么做那件事。" },
  1659: { translation: "我们只能咬牙忍着。" },
  1668: { translation: "每天早上，我都会喝一杯咖啡。" },
  1674: { text: "Steel production will rise by two percent compared with last month.", translation: "本月钢铁产量预计比上月增长百分之二。", category: "work" },
  1690: { translation: "你更想喝茶还是咖啡？" },
  1692: { translation: "我不喜欢茶，所以早餐通常喝咖啡。" },
  1697: { text: "I'll treat you to a cup of coffee." },
  1762: { translation: "你可以选择红茶、咖啡或牛奶。" },
  1873: { text: "The police will ask you to describe what happened.", translation: "警察会请你描述事情的经过。" },
  1911: { text: "Bill left home early so he could arrive before the meeting started.", translation: "比尔很早就出门了，好在会议开始前赶到。", category: "work" },
  1924: { category: "work" },
  1926: { text: "This kind of problem should be possible to solve.", translation: "这类问题应该可以解决。", category: "help" },
  1928: { category: "shopping" },
  1930: { text: "Studying a country's language is not enough to understand its culture.", translation: "只学习一个国家的语言，还不足以了解它的文化。", category: "work" },
  1937: { text: "A short walk can help you work up an appetite for breakfast.", translation: "短暂散步可以让你在早餐前产生食欲。", category: "food" },
  1942: { text: "Drop by drop, even a little water can eventually form a lake.", translation: "一滴一滴地积累，少量的水最终也能汇成湖泊。", category: "daily" },
  1946: { translation: "这么厚的一本书，我一周内读不完。" },
  1953: { translation: "只图便宜，最后反而可能花更多钱。" },
  1954: { translation: "这张火车票可以退款吗？" },
  1964: { category: "work" },
  1967: { translation: "我爱你。你有没有可能也爱上我？" },
  1970: { category: "work" },
  1974: { text: "Did you buy it at the market near the station?", translation: "你是在车站附近的市场买的吗？", category: "shopping" },
  1980: { translation: "我在医院住了一周。" },
  1992: { translation: "我和健二在同一所学校上学。" },
  1998: { translation: "你不必继续留在医院。" },
  2002: { category: "shopping" },
  2008: { translation: "你的法语说得很好。我希望也能说得和你一样好。" },
  2010: { text: "Because we only have one Earth, we need to better understand how to care for it.", translation: "我们只有一个地球，因此需要更好地了解该如何爱护它。" },
  2012: { text: "Sometimes, I wish I could travel through time and meet my childhood self.", translation: "有时候，我真希望能穿越时空，见一见小时候的自己。" },
  2014: { translation: "不管你愿不愿意，我们都必须那样做。" },
  2021: { translation: "如果你毫无品格可言，人们就不会信任你。" },
  2022: { category: "help" },
  2026: { translation: "人类很快就能去月球旅行了。" },
  2028: { category: "travel" },
  2030: { text: "Being able to read a language does not automatically mean that you can speak it fluently.", translation: "能读懂一种语言，并不意味着你自然就能流利地说出来。" },
  2034: { category: "travel" },
  2038: { text: "A small general store can sell many different kinds of everyday household items.", translation: "小型杂货店可以出售多种日常家居用品。", category: "shopping" },
  2058: { translation: "如果你回家前能买些面包，那就太好了。" },
  2063: { text: "You could spend a few days relaxing by the sea while I'm away on business.", translation: "我出差期间，你可以去海边放松几天。", category: "travel" },
  2091: { translation: "真心希望他们结为夫妻后能够幸福生活、白头偕老。" },
  2104: { text: "I am a makeup artist, and I help clients choose a style that suits them.", translation: "我是一名化妆师，会帮助顾客选择适合自己的风格。", category: "work" },
  2105: { text: "This book gives a clear introduction to everyday life in the United States.", translation: "这本书清楚地介绍了美国的日常生活。", category: "work" },
  2111: { translation: "哦，现在想起来了——我把它落在填申请表的那张桌子上了。" },
  2137: { text: "When do you usually get up on Sundays, and when do you go to sleep?", translation: "你星期天通常几点起床，又几点睡觉？" },
  2141: { translation: "你怎么知道他们只是因为你的表情很滑稽，才用奇怪的眼神看你呢？" },
  2158: { translation: "嗯，好像出什么事了。等一下，我来弄清楚。" },
  2165: { text: "Bill checked the train schedule the night before so he would not miss his morning appointment.", translation: "比尔前一晚查看了列车时刻，以免错过第二天早上的约会。", category: "travel" },
  2178: { translation: "牛奶一旦倒进咖啡里，就无法再把它们分开。" },
  2184: { translation: "你真的以为我会眼睁睁看着你惹上麻烦吗？我会把眼睛闭上。" },
  2218: { translation: "如果一个男生爱你，他会时时刻刻想着你。" },
  2228: { text: "What do I think, you ask? Well, I'll give you my honest opinion.", translation: "你问我是怎么想的？好吧，我就坦白告诉你。" },
  2248: { translation: "晚一天再买也没什么大不了的！" },
  2263: { text: "Tom is in a difficult situation, so we should offer practical help as soon as possible.", translation: "汤姆遇到了困难，我们应该尽快提供实际帮助。", category: "help" },
  2289: { text: "Whenever I eat at a Japanese restaurant, I try to use chopsticks correctly.", translation: "每次去日本餐厅吃饭，我都会尽量正确使用筷子。", category: "food" },
  2304: { translation: "你有什么不开心的事？说出来，让大家安慰你、帮你振作一点。" },
  2309: { text: "If you wear that to the office, people may think it is too casual.", translation: "如果你穿那身衣服去办公室，别人可能会觉得太随便。", category: "work" },
  2311: { translation: "每次看到这张照片，我都会想起在村里度过的那些快乐时光。" },
  2353: { translation: "你想吃面条还是米饭？想喝果汁还是咖啡？" },
  2362: { text: "Which article do you think was read most often on Japanese Wikipedia this year?", translation: "你觉得今年日文维基百科上哪篇文章的阅读次数最多？", category: "work" },
  2409: { translation: "由于政府关注不足，这个地区仍然欠发达。", category: "work" },
  2440: { translation: "安妮，今天下午剩下的时间，你就站在黑板前面的讲台上。" },
  2462: { translation: "我更喜欢能乐而不是歌舞伎，因为我觉得前者比后者更优雅。" },
  2474: { text: "If the kitchen smells like smoke, turn off the stove and open the windows immediately.", translation: "如果厨房里有烟味，请立即关掉炉灶并打开窗户。", category: "help" },
  2503: { text: "He had heard the same complaint many times, and this time he could not bear it.", translation: "同样的抱怨他已经听过很多次，这次终于忍受不了了。" },
  2501: { translation: "食物快要用完时，他不得不寻找新的住处。" },
  2507: { translation: "我今天早上只吃了一片吐司，喝了一杯咖啡。" },
  2508: { translation: "我太着急了，忘了锁门。" },
  2523: { translation: "请给我们两杯茶和一杯咖啡，好吗？" },
  2529: { text: "If we have to make this decision today, I would rather wait until tomorrow.", translation: "如果今天必须作出决定，我宁愿等到明天再说。", category: "daily" },
  2532: { translation: "如果你觉得教育昂贵，那就等着看看无知会让你付出什么代价。" },
  2534: { text: "You may not realize how small Japan is until you travel abroad by yourself.", translation: "你可能要亲自出国旅行后，才会意识到日本有多小。", category: "travel" },
  2539: { translation: "不然你自己去瑞士玩，我和姐姐去爱沙尼亚。", category: "travel" },
  2549: { text: "In China, you can usually buy train tickets online or at the station.", translation: "在中国，通常可以在网上或车站购买火车票。", category: "travel" },
  2555: { translation: "我想知道我们有没有足够的钱，给汤姆买下他想要的那幅画。" },
  2566: { text: "I wonder why Tom thinks I don't need to do that task again.", translation: "我想知道汤姆为什么认为我不必再做一遍那项任务。" },
  2584: { text: "I don't usually make exceptions, but this time I'm willing to make one for you.", translation: "我通常不会破例，不过这次我愿意为你破例。", category: "social" },
  2633: { translation: "不是每个人都喜欢喝茶。比如我就喜欢咖啡。" },
  2646: { translation: "你决定好骑自行车还是坐公交车进城了吗？" },
  2642: { text: "Honest conversations are easier when everyone listens carefully and avoids pretending to agree.", translation: "每个人都认真倾听、不假装赞同时，坦诚交流会容易得多。", category: "social" },
  2643: { translation: "这份工作还是得由我来做，别人处理不了。" },
  2662: { translation: "如果我中了彩票，就能过上富足的生活。" },
  2708: { text: "It's five o'clock. If you post your letter now, it might still arrive on time.", translation: "现在五点。如果你马上寄信，也许还能及时送到。" },
  2711: { translation: "怀旧时，我们往往会把童年想成一段几乎始终快乐的时光。" },
  2714: { text: "When you write a short message, clarity matters because every word should help the reader.", translation: "写简短消息时，表达清楚很重要，因为每个词都应该帮助读者理解。", category: "social" },
  2716: { text: "People appreciate someone who listens carefully and chooses their words before speaking to others.", translation: "人们会欣赏认真倾听、开口前仔细斟酌用词的人。", category: "social" },
  2729: { text: "It's raining outside. Would you like to stay here a little longer until it stops?", translation: "外面在下雨。你愿意在这里多待一会儿，等雨停吗？", category: "social" },
  2742: { text: "You can make your computer run faster by adding more memory when it starts feeling slow.", translation: "电脑开始变慢时，增加内存可以让它运行得更快。", category: "work" },
  2749: { text: "We can often learn something valuable from the difficult situations we face in everyday life.", translation: "我们常常能从日常生活中的困境里学到宝贵的东西。" },
  2763: { translation: "火车太拥挤了，我一路上都只能站着。" },
  2787: { text: "It's difficult to slow down and enjoy reading a good book in our busy lives.", translation: "生活忙碌时，我们很难慢下来好好读一本书。" },
  2794: { category: "daily" },
  2796: { text: "He made an official visit to the French president in Paris two days ago.", translation: "两天前，他在巴黎正式拜访了法国总统。", category: "work" },
  2814: { text: "One day, the police questioned a group of people, and the girl was among them.", translation: "有一天，警方询问了一群人，那个女孩也在其中。", category: "help" },
  2826: { text: "A democracy works best when free citizens respect the decisions made by the majority.", translation: "自由公民尊重多数人的决定时，民主制度才能更好地运作。", category: "work" },
  2835: { text: "As a result, English speakers can usually understand what learners from other countries are saying.", translation: "因此，以英语为母语的人通常能听懂其他国家学习者说的话。", category: "work" },
  2845: { text: "Tom's main problem is that he rarely understands why other people are joking.", translation: "汤姆的主要问题是，他很少能听懂别人为什么在开玩笑。", category: "social" },
  2847: { translation: "我走在拥挤的街道上，突然听到一声尖叫。" },
  2857: { text: "I wouldn't work for Tom again, no matter how much money he offered me.", translation: "无论汤姆给多少钱，我都不会再为他工作。", category: "work" },
  2885: { translation: "火车太挤了，我们一路站到了大阪。" },
  2895: { text: "Before making an important decision, I like to sleep on it and talk with someone I trust.", translation: "做重要决定前，我喜欢先考虑一晚，再和信任的人聊一聊。", category: "social" },
  2899: { text: "In many parts of China, rice is common in the south and wheat foods in the north.", translation: "在中国许多地区，南方常吃米饭，北方常吃面食。", category: "food" },
  2902: { text: "The woman began to feel unwell shortly after she finished eating the meat.", translation: "那位女士吃完肉不久后就开始感觉不舒服。", category: "help" },
  2905: { text: "Sami has to go to his chemistry class, but he will see you afterward.", translation: "萨米得去上化学课，不过下课后会来见你。", category: "work" },
  2908: { text: "Tom is the company director in name only; his son makes all the important decisions.", translation: "汤姆只是名义上的公司负责人，所有重要决定都由他的儿子来做。", category: "work" },
  2922: { translation: "世上没有什么真正值得拥有或去做的事，是可以不经过努力、痛苦和困难就得到的。" },
  2927: { text: "Alice didn't know where to find the book, so she asked her mother for help.", translation: "爱丽丝不知道去哪里找那本书，于是向妈妈求助。", category: "help" },
  2928: { text: "Never drive after drinking alcohol, even when you feel completely fine and alert.", translation: "喝酒后绝不要开车，即使你觉得自己完全清醒、状态良好。", category: "help" },
  2932: { translation: "全世界计算机中的信息，有百分之八十是用英语写的。" },
  2934: { text: "As usual, Mike arrived late for the team meeting that was held this afternoon.", translation: "和往常一样，迈克参加今天下午的团队会议时又迟到了。", category: "work" },
  2937: { text: "The police asked Tom and Mary to describe what they saw near the station.", translation: "警察请汤姆和玛丽描述他们在车站附近看到的情况。", category: "help" },
  2938: { text: "He has written a book, but he has no money to publish it.", translation: "他写了一本书，但是没有钱出版。", category: "work" },
  2947: { text: "I'm extremely angry right now, so I need a few quiet minutes to calm down.", translation: "我现在非常生气，需要安静几分钟让自己冷静下来。" },
  2951: { text: "I could have some beef noodle soup or rice with soybean paste. Either is fine.", translation: "牛肉面或豆酱拌饭都可以，我都没问题。" },
  2974: { translation: "我完全忘了去医院的预约。你怎么没提醒我？" },
  2978: { text: "I am in Lyon, but maybe I'll go to Paris to look for a job.", translation: "我现在在里昂，不过也许会去巴黎找工作。" },
  2979: { translation: "汤姆下次考试必须考得更好，否则这门课会不及格。" },
  2983: { translation: "最近咖啡短缺，引发了许多问题。" },
  2985: { translation: "桌上有个盘子，里面放着三个煎蛋。" },
  2989: { translation: "市政府举行了一次大型会议，旨在促进跨部门合作。", category: "work" },
  2993: { text: "The ages of the two children added together were equal to their father's age.", translation: "两个孩子的年龄加起来等于他们父亲的年龄。", category: "social" },
  2995: { text: "Watching a film in English can help you notice how people speak in everyday situations.", translation: "观看英语电影可以帮助你留意人们在日常情境中的表达方式。", category: "work" },
  2998: { text: "He didn't come because he had to work, not because he was sick.", translation: "他没来是因为要工作，不是因为生病。", category: "work" },
  563: { text: "Do it however you like.", translation: "你喜欢怎么做都可以。" },
  661: { text: "Where is the nearest police station?", translation: "最近的警察局在哪里？", category: "help" },
  1286: { text: "A magazine may cover a story in more depth than a newspaper.", translation: "杂志对一件事的报道可能比报纸更深入。", category: "work" },
  1307: { text: "Can you spend a little more time studying English?", translation: "你能多花一点时间学习英语吗？", category: "work" },
  1397: { translation: "我更喜欢屏幕大的手机。", category: "shopping" },
  1483: { translation: "不好意思，我可以借用一下吗？" },
  1553: { text: "Whatever you do, the outcome will still be the same.", translation: "无论你怎么做，结果都还是一样。" },
  1642: { translation: "真正的科学家不会那样想。", category: "work" },
  1650: { translation: "我今天下午会用电子邮件发送。" },
  1675: { translation: "世界人口不久将翻一番。" },
  1779: { translation: "你打算怎么用这笔钱？" },
  2117: { text: "When many enemies appear before you, look back and remember that you have many allies too.", translation: "当许多敌人出现在你面前时，回头看看，别忘了你也有许多盟友。", category: "social" },
  2144: { translation: "如果需要更多屏幕空间，可以关闭侧边栏。", category: "work" },
  2476: { translation: "那您跟我来一下吧。我们去仓库看看，说不定能在那里找到。", category: "shopping" },
  2525: { translation: "我们很可能会去，不过要看天气后再决定。", category: "travel" },
  2593: { translation: "我和同事做着同样的工作，但公司答应很快给她升职。" },
  2596: { text: "If you have concerns about our company, please explain them clearly so we can respond.", translation: "如果你对我们公司有意见，请清楚说明，以便我们回应。", category: "work" },
  2722: { translation: "在电子邮件时代，收到朋友寄来的纸质信件会让我格外开心。", category: "social" },
  2907: { text: "Being open to love can feel difficult, but meaningful relationships are worth the effort.", translation: "敞开心扉去爱并不容易，但有意义的关系值得为之努力。", category: "social" },
  2967: { translation: "父母努力让孩子明白诚实和勤奋的重要性。" },
  77: { translation: "我能帮上什么忙吗？" },
  109: { translation: "要我给你拿点喝的吗？" },
  113: { translation: "如果你想去，就去吧。" },
  122: { translation: "你想要什么，我都会给你。" },
  144: { text: "Where would you like to explore?", translation: "你想去哪里逛逛？" },
  149: { translation: "这事你可以放心。" },
  202: { translation: "你能把音量调小一点吗？" },
  256: { text: "Do as I tell you.", translation: "照我说的做。" },
  264: { translation: "你什么时候需要它？" },
  295: { translation: "这个还能做什么？" },
  305: { translation: "你还能做到吗？" },
  310: { text: "Don't you have any classes today?", translation: "你今天没有课吗？" },
  325: { translation: "我喜欢你微笑的样子。" },
  333: { translation: "可以给我们安排一张室外的餐桌吗？" },
  340: { translation: "我能要点吃的吗？" },
  374: { translation: "你怎么解释那件事？" },
  475: { translation: "会出什么问题呢？" },
  479: { translation: "你愿意付多少就付多少。" },
  497: { translation: "有可能，有可能。" },
  513: { translation: "我可以聊一会儿。" },
  552: { translation: "儿子，我爱你。" },
  574: { translation: "我想我有一个问题。" },
  579: { category: "travel", translation: "我们要在哪里换乘？" },
  632: { translation: "我非常想去。" },
  651: { translation: "我能在一周内完成。" },
  710: { translation: "这个项目将如何运作？" },
  725: { text: "Is your class over?", translation: "你下课了吗？" },
  743: { translation: "你在那所学校上学吗？" },
  756: { category: "shopping", text: "Do you accept credit cards?", translation: "你们接受信用卡付款吗？" },
  829: { translation: "真是活到老，学到老。" },
  841: { translation: "那所新学校什么时候开学？" },
  920: { translation: "我必须写封信吗？" },
  925: { translation: "我当然应该读这本书。" },
  969: { translation: "乘坐 5 号轨道上的任意一班列车。" },
  982: { translation: "不要喝这水！" },
  1132: { text: "I do not know how to read or write.", translation: "我不会读书写字。" },
  1144: { translation: "我希望您很快就能康复。" },
  1174: { translation: "我不知道该怎么熬过这个月。" },
  1186: { translation: "我必须请你照那样做。" },
  1280: { text: "I hope that we do not have to wait long.", translation: "希望我们不用等太久。" },
  1290: { translation: "睡觉前不要吃东西。" },
  1302: { translation: "你能游得和他一样快吗？" },
  1304: { translation: "你怎么负担得起这样的地方？" },
  1322: { translation: "万一他迟到了怎么办？" },
  1334: { translation: "请等到这个月底。" },
  1367: { text: "I'm sorry to have kept you waiting so long.", translation: "抱歉，让你久等了。" },
  1373: { translation: "我为什么必须去上学？" },
  1384: { text: "Please make sure you complete the full course of treatment.", translation: "请务必完成整个疗程。" },
  1449: { translation: "今天的小餐馆，将来可能会发展成一家大酒店。" },
  1498: { translation: "火车一定会准时到达。" },
  1516: { translation: "他们明天下午不在学校。" },
  1522: { translation: "他们会尽快把事情办好。" },
  1548: { translation: "你刚才把一个玩具放在了桌上。" },
  1688: { translation: "能把这块肉再做熟一点吗？" },
  1747: { text: "I wish I hadn't said that at the party.", translation: "真希望我当时没在聚会上说那句话。" },
  1786: { translation: "你给他们的钱会得到妥善利用。" },
  1795: { translation: "比尔很早起床，以便赶上第一班火车。" },
  1808: { translation: "我起得足够早，能赶上第一班火车。" },
  1825: { text: "The train is about to leave; we can barely catch it.", translation: "火车就要开了，我们勉强能赶上。" },
  1895: { translation: "如果你有任何问题，随时打电话来。" },
  1900: { translation: "我们必须学会接纳身边的人。" },
  1910: { translation: "英国人很重视法律和秩序。" },
  1989: { translation: "我们成功赶上了末班火车。" },
  2037: { translation: "我想尽快搬出这间狭小的房间。" },
  2046: { translation: "我想，从长远来看，情况就不一样了。" },
  2051: { translation: "比如，如果我要去市中心，该坐哪路公交车？" },
  2070: { text: "If one day you realized you had no useful skills, what would you do?", translation: "如果有一天你发现自己没有什么实用技能，你会怎么办？" },
  2118: { text: "Thank you for helping me. Please turn off the light because I want to sleep.", translation: "谢谢你帮了我。请把灯关掉，我想睡觉了。" },
  2123: { text: "Would you like to send it by air mail or by surface mail?", translation: "您想寄航空邮件还是平邮？" },
  2175: { translation: "她只有星期天才能去公司做志愿工作。" },
  2181: { translation: "如果你不赶时间，要不要喝杯茶什么的？" },
  2189: { text: "I don't know the train schedule. Could you check the departure times for me?", translation: "我不知道列车时刻。你能帮我查一下发车时间吗？" },
  2231: { translation: "然而，一看到火车站的情况，我就开始后悔这个决定了。" },
  2239: { translation: "你每周去电影院看几次电影？" },
  2251: { translation: "你需要提交几张照片，填写一张表格，并办好签证。" },
  2306: { translation: "以前我盼着成为现在的自己；如今我却希望回到那时的样子。" },
  2358: { text: "Put your hard hat on. A brick could easily fall on your head here.", translation: "戴上安全帽。这里可能会有砖块掉下来砸到你的头。" },
  2360: { translation: "由于错过了火车，我不得不等了大约一个小时才等到下一班。" },
  2370: { translation: "据我所知，他是这所学校个子最矮的学生。" },
  2483: { translation: "这里看起来还和很久以前一样。" },
  2553: { translation: "我打算接受那家公司的录用邀请，担任他们的营销部经理。" },
  2560: { translation: "我小时候常在放学后打棒球。" },
  2586: { text: "He is very popular, so whenever he gets into trouble, his friends are happy to help.", translation: "他很受欢迎，所以每当他遇到困难，朋友们都乐意帮忙。" },
  2600: { translation: "工作完成后，通常在五点半左右，我就回家吃晚饭。" },
  2606: { text: "Customers who buy a new device can enjoy an additional trial period as a special offer.", translation: "购买新设备的顾客可以享受额外试用期优惠。" },
  2631: { translation: "阿姨，不用麻烦了。给我一杯白开水就够了。" },
  2669: { translation: "我不知道该把这当成赞美还是侮辱。" },
  2672: { translation: "生活中有得有失，但有些事也强求不来。" },
  2676: { translation: "你知道公园街上以前有家中餐馆吗？" },
  2682: { text: "It is kind of you to go out of your way to help me.", translation: "你特意来帮我，真是太好了。" },
  2726: { translation: "我的名字排在名单最前面，所以我第一个被叫进办公室。" },
  2732: { text: "The application allows you to quickly calculate your body mass index, also known as BMI.", translation: "这个应用可以让你快速计算身体质量指数，也就是 BMI。" },
  2736: { translation: "这只是你我之间的秘密，可别说漏嘴。" },
  2743: { translation: "它能编辑你不满意的照片，然后再把它们打印出来。" },
  2756: { translation: "城市里各种各样的噪音总让他烦恼。" },
  2765: { text: "Why is it that I still can't learn English well after all this time?", translation: "为什么学了这么久，我还是学不好英语？" },
  2795: { translation: "哈里因手臂骨折，不得不退出比赛。" },
  2800: { translation: "我找不到眼镜了，可能把它落在火车上了。" },
  2859: { translation: "马克·诺弗勒刚弹出《Money for Nothing》的前几个小节，现场大批观众便高声欢呼。" },
  2864: { translation: "他住院时，妻子寄来的大多数信都是护士读给他听的。" },
  2921: { text: "Edinburgh offers a lively city experience with traditional character, historic buildings, and many tourist attractions.", translation: "爱丁堡是一座热闹且富有传统气息的城市，拥有许多历史建筑和旅游景点。" },
  2925: { translation: "汤姆的妈妈是一名护士，她工作的医院就在玛丽住处的街对面。" },
  2939: { text: "On a crowded train, I would rather wait for a seat than stand by the door.", translation: "列车很拥挤时，我宁愿等个座位，也不愿站在车门旁。" },
  2996: { translation: "他等火车时听着音乐，还发了短信。" },
};
const sentencePackCache = new Map<number, Promise<SentenceItem[]>>();

async function fetchSentencePack(pack: 1 | 2 | 3) {
  const start = (pack - 1) * 1000 + 1;
  const expectedBand: SentenceBand = pack === 1 ? "short" : pack === 2 ? "medium" : "long";
  const categories = new Set<SentenceItem["category"]>(["daily", "social", "food", "travel", "shopping", "work", "help"]);
  const validate = (value: unknown): value is SentenceItem[] => Array.isArray(value)
    && value.length === 1000
    && value.every((item, index) => item && typeof item === "object"
      && (item as SentenceItem).id === start + index
      && (item as SentenceItem).length === expectedBand
      && typeof (item as SentenceItem).text === "string"
      && (item as SentenceItem).text.trim().length > 0
      && typeof (item as SentenceItem).translation === "string"
      && (item as SentenceItem).translation.trim().length > 0
      && Number.isInteger((item as SentenceItem).sourceId)
      && (item as SentenceItem).sourceId > 0
      && Number.isInteger((item as SentenceItem).translationId)
      && (item as SentenceItem).translationId > 0
      && typeof (item as SentenceItem).author === "string"
      && (item as SentenceItem).author.trim().length > 0
      && (item as SentenceItem).author !== "\\N"
      && typeof (item as SentenceItem).translationAuthor === "string"
      && (item as SentenceItem).translationAuthor.trim().length > 0
      && (item as SentenceItem).translationAuthor !== "\\N"
      && categories.has((item as SentenceItem).category));
  return fetchJsonWithRecovery(`/data/tatoeba-sentences-${pack}.json?rev=${CONTENT_REVISION}`, validate);
}

export function loadSentencePack(pack: 1 | 2 | 3) {
  if (!sentencePackCache.has(pack)) {
    sentencePackCache.set(pack, fetchSentencePack(pack).then((items) => items.map((item) => {
      const correction = SENTENCE_CORRECTIONS[item.id];
      return correction ? { ...item, ...correction, adapted: Boolean(correction.text || correction.translation) } : item;
    })).catch((error) => {
      sentencePackCache.delete(pack);
      throw error;
    }));
  }
  return sentencePackCache.get(pack)!;
}
