import type { WordItem } from "./data";

type WordCardCorrection = Pick<WordItem, "example" | "translation" | "exampleForm" | "collocations"> & Partial<Pick<WordItem, "meaning">>;

// NGSL keys are lowercase; learner-facing English still follows spelling rules.
export function normalizeWordDisplay(item: WordItem): WordItem {
  return { ...item, word: item.word === "i" ? "I" : item.word, collocations: item.collocations.map((phrase) => phrase.replace(/\bi\b/g, "I")) };
}

// The source corpus remains unchanged. These display-only corrections keep the
// most frequently encountered cards short, natural and useful for speaking.
export const wordCardCorrections: Record<string, WordCardCorrection> = {
  down: { example: "Please sit down.", translation: "请坐下。", exampleForm: "down", collocations: ["sit down", "walk down the stairs"] },
  little: { example: "Could you cook this meat a little more?", translation: "能把这块肉再做熟一点吗？", exampleForm: "little", collocations: ["a little more", "a little water"] },
  something: { example: "I have something to tell you.", translation: "我有件事想告诉你。", exampleForm: "something", collocations: ["something to tell you", "something useful"] },
  put: { example: "Please put the bag on the chair.", translation: "请把包放在椅子上。", exampleForm: "put", collocations: ["put the bag down", "put it on the chair"] },
  another: { example: "Could I have another cup of coffee?", translation: "可以再给我一杯咖啡吗？", exampleForm: "another", collocations: ["another cup", "another day"] },
  each: { example: "Each student has a book.", translation: "每个学生都有一本书。", exampleForm: "Each", collocations: ["each student", "each day"] },
  case: { meaning: "情况；事例；以防（in case）", example: "Take an umbrella in case it rains.", translation: "带把伞，以防下雨。", exampleForm: "case", collocations: ["in case", "in case it rains"] },
  message: { example: '"Shall I take a message?" "No, thank you."', translation: "“需要我帮您记下口信吗？”“不用了，谢谢。”", exampleForm: "message", collocations: ["take a message", "leave a message"] },
  double: { meaning: "两倍的；加倍", example: "Ten is double five.", translation: "十是五的两倍。", exampleForm: "double", collocations: ["double the price", "a double room"] },
  cook: { example: "Could you cook this meat a little more?", translation: "能把这块肉再做熟一点吗？", exampleForm: "cook", collocations: ["cook the meat", "cook dinner"] },
  meal: { example: "She always clears the table after a meal.", translation: "她总是在饭后收拾桌子。", exampleForm: "meal", collocations: ["after a meal", "a hot meal"] },
  brand: { example: "I like this brand of shoes.", translation: "我喜欢这个牌子的鞋。", exampleForm: "brand", collocations: ["this brand", "a clothing brand"] },
  meat: { example: "Could you cook this meat a little more?", translation: "能把这块肉再做熟一点吗？", exampleForm: "meat", collocations: ["cook the meat", "fresh meat"] },
  sugar: { example: "There is no sugar left in the pot.", translation: "罐子里没有糖了。", exampleForm: "sugar", collocations: ["no sugar", "a spoonful of sugar"] },
  do: { meaning: "做；进行；助动词", example: "I do some exercise after work.", translation: "我下班后会做些运动。", exampleForm: "do", collocations: ["do some exercise", "after work"] },
  as: { example: "I work as a teacher.", translation: "我是一名老师。", exampleForm: "as", collocations: ["work as", "as a teacher"] },
  at: { example: "Meet me at the station.", translation: "在车站和我见面。", exampleForm: "at", collocations: ["at the station", "meet at"] },
  she: { example: "She lives near the park.", translation: "她住在公园附近。", exampleForm: "She", collocations: ["she lives", "lives near"] },
  but: { example: "I wanted to go, but I was tired.", translation: "我想去，但是我累了。", exampleForm: "but", collocations: ["but I was", "go, but"] },
  from: { example: "This train comes from the airport.", translation: "这班火车从机场开来。", exampleForm: "from", collocations: ["comes from", "from the airport"] },
  by: { example: "We can get there by bus.", translation: "我们可以坐公交车到那里。", exampleForm: "by", collocations: ["by bus", "get there by"] },
  will: { example: "I will call you tonight.", translation: "我今晚会给你打电话。", exampleForm: "will", collocations: ["will call", "will call you"] },
  or: { example: "Would you like tea or coffee?", translation: "你想喝茶还是咖啡？", exampleForm: "or", collocations: ["tea or coffee", "or coffee"] },
  say: { example: "What did you say?", translation: "你刚才说什么？", exampleForm: "say", collocations: ["did you say", "what did you say"] },
  go: { example: "I need to go home now.", translation: "我现在需要回家。", exampleForm: "go", collocations: ["go home", "need to go"] },
  so: { example: "I was tired, so I went home.", translation: "我累了，所以回家了。", exampleForm: "so", collocations: ["so I went", "tired, so"] },
  all: { example: "All the rooms are full.", translation: "所有房间都满了。", exampleForm: "All", collocations: ["all the rooms", "rooms are full"] },
  if: { example: "Call me if you need help.", translation: "如果你需要帮助，就给我打电话。", exampleForm: "if", collocations: ["if you need", "call me if"] },
  about: { example: "Tell me about your trip.", translation: "跟我说说你的旅行吧。", exampleForm: "about", collocations: ["about your trip", "tell me about"] },
  can: { example: "Can you help me?", translation: "你能帮我吗？", exampleForm: "Can", collocations: ["can you help", "help me"] },
  which: { example: "Which bus goes to the airport?", translation: "哪班公交车去机场？", exampleForm: "Which", collocations: ["which bus", "goes to the airport"] },
  there: { example: "There is a café near the hotel.", translation: "酒店附近有一家咖啡馆。", exampleForm: "There", collocations: ["there is", "near the hotel"] },
  know: { example: "Do you know the way to the station?", translation: "你知道去车站的路吗？", exampleForm: "know", collocations: ["do you know", "know the way"] },
  more: { example: "Could I have some more water?", translation: "可以再给我一些水吗？", exampleForm: "more", collocations: ["some more water", "have some more"] },
  who: { example: "Who is that person?", translation: "那个人是谁？", exampleForm: "Who", collocations: ["who is", "that person"] },
  like: { example: "I like this restaurant.", translation: "我喜欢这家餐厅。", exampleForm: "like", collocations: ["like this", "this restaurant"] },
  think: { example: "I think this is a good idea.", translation: "我觉得这是个好主意。", exampleForm: "think", collocations: ["I think", "think this is"] },
  make: { example: "Can you make some coffee?", translation: "你能泡点咖啡吗？", exampleForm: "make", collocations: ["make some coffee", "can you make"] },
  time: { example: "What time is it?", translation: "现在几点？", exampleForm: "time", collocations: ["what time", "time is it"] },
  what: { example: "What do you need?", translation: "你需要什么？", exampleForm: "What", collocations: ["what do you", "what do you need"] },
  up: { example: "Please stand up.", translation: "请站起来。", exampleForm: "up", collocations: ["stand up", "please stand up"] },
  out: { example: "Let's go out for dinner.", translation: "我们出去吃晚饭吧。", exampleForm: "out", collocations: ["go out", "out for dinner"] },
  people: { example: "Many people take this bus.", translation: "很多人坐这班公交车。", exampleForm: "people", collocations: ["many people", "people take"] },
  no: { example: "No, thank you.", translation: "不用了，谢谢。", exampleForm: "No", collocations: ["no, thank you"] },
  well: { example: "You speak English very well.", translation: "你的英语说得很好。", exampleForm: "well", collocations: ["very well", "speak English well"] },
  because: { example: "I stayed home because it was raining.", translation: "因为下雨，我待在家里。", exampleForm: "because", collocations: ["because it was", "home because"] },
  very: { example: "The room is very quiet.", translation: "这个房间非常安静。", exampleForm: "very", collocations: ["very quiet", "is very"] },
  just: { example: "I just got here.", translation: "我刚到这里。", exampleForm: "just", collocations: ["just got here", "I just"] },
  come: { example: "Can you come tomorrow?", translation: "你明天能来吗？", exampleForm: "come", collocations: ["come tomorrow", "can you come"] },
  could: { example: "Could you say that again?", translation: "你能再说一遍吗？", exampleForm: "Could", collocations: ["could you", "say that again"] },
  work: { example: "I work at a hotel.", translation: "我在一家酒店工作。", exampleForm: "work", collocations: ["work at", "at a hotel"] },
  than: { example: "This bag is cheaper than that one.", translation: "这个包比那个便宜。", exampleForm: "than", collocations: ["cheaper than", "than that one"] },
  now: { example: "I am busy right now.", translation: "我现在正忙。", exampleForm: "now", collocations: ["right now", "busy now"] },
  then: { example: "Let's eat first and then leave.", translation: "我们先吃饭，然后再走。", exampleForm: "then", collocations: ["and then", "then leave"] },
  into: { example: "Please put the key into the box.", translation: "请把钥匙放进盒子里。", exampleForm: "into", collocations: ["into the box", "put into"] },
  only: { example: "I only have ten minutes.", translation: "我只有十分钟。", exampleForm: "only", collocations: ["only have", "only ten minutes"] },
  want: { example: "I want to buy a ticket.", translation: "我想买一张票。", exampleForm: "want", collocations: ["want to buy", "buy a ticket"] },
  first: { example: "This is my first time here.", translation: "这是我第一次来这里。", exampleForm: "first", collocations: ["first time", "my first"] },
  way: { example: "Is this the right way to the station?", translation: "这是去车站的正确方向吗？", exampleForm: "way", collocations: ["right way", "way to the station"] },
  find: { example: "Where can I find a taxi?", translation: "我在哪里能找到出租车？", exampleForm: "find", collocations: ["find a taxi", "where can I find"] },
  over: { example: "The meeting is over.", translation: "会议结束了。", exampleForm: "over", collocations: ["is over", "meeting is over"] },
  any: { example: "Do you have any questions?", translation: "你有什么问题吗？", exampleForm: "any", collocations: ["any questions", "have any"] },
  day: { example: "Have a nice day.", translation: "祝你今天愉快。", exampleForm: "day", collocations: ["nice day", "have a nice day"] },
  where: { example: "Where is the bathroom?", translation: "洗手间在哪里？", exampleForm: "Where", collocations: ["where is", "the bathroom"] },
  most: { example: "Most shops close at nine.", translation: "大多数商店九点关门。", exampleForm: "Most", collocations: ["most shops", "shops close"] },
  should: { example: "You should get some rest.", translation: "你应该休息一下。", exampleForm: "should", collocations: ["should get", "get some rest"] },
  much: { example: "How much does this cost?", translation: "这个多少钱？", exampleForm: "much", collocations: ["how much", "much does"] },
  how: { example: "How are you?", translation: "你好吗？", exampleForm: "How", collocations: ["how are you"] },
  back: { example: "I'll be back soon.", translation: "我很快回来。", exampleForm: "back", collocations: ["be back", "back soon"] },
  mean: { meaning: "意思是；意味着；表示", example: "What does this word mean?", translation: "这个单词是什么意思？", exampleForm: "mean", collocations: ["word mean", "what does this mean"] },
  still: { meaning: "仍然；还是；依旧", example: "I got up while it was still dark.", translation: "我起床时天还是黑的。", exampleForm: "still", collocations: ["still dark", "still waiting"] },
  meet: { meaning: "遇见；会面；认识", example: "It was a pleasure to meet you.", translation: "很高兴见到你。", exampleForm: "meet", collocations: ["meet you", "meet at the station"] },
  even: { example: "Even this small room is comfortable.", translation: "即使这个小房间也很舒适。", exampleForm: "Even", collocations: ["even this", "small room"] },
  may: { example: "May I sit here?", translation: "我可以坐这里吗？", exampleForm: "May", collocations: ["may I", "sit here"] },
  here: { example: "Please wait here.", translation: "请在这里等。", exampleForm: "here", collocations: ["wait here", "please wait"] },
  such: { example: "I've never seen such a beautiful view.", translation: "我从没见过这么美的景色。", exampleForm: "such", collocations: ["such a", "beautiful view"] },

  get: { example: "I hope you will get well soon.", translation: "希望你很快好起来。", exampleForm: "get", collocations: ["get well", "get well soon"] },
  woman: { example: "The woman at the desk helped me.", translation: "服务台的那位女士帮助了我。", exampleForm: "woman", collocations: ["the woman", "woman at the desk"] },
  provide: { example: "I will provide you with all the necessary information.", translation: "我会向你提供所有必要的信息。", exampleForm: "provide", collocations: ["provide information", "provide you with"] },
  result: { example: "I am far from satisfied with the result.", translation: "我对这个结果远不满意。", exampleForm: "result", collocations: ["the result", "satisfied with the result"] },
  lead: { example: "She will lead the team this year.", translation: "今年她将带领这个团队。", exampleForm: "lead", collocations: ["lead the team", "lead a group"] },
  form: { example: "Please complete this form before the meeting.", translation: "请在会前填好这张表格。", exampleForm: "form", collocations: ["complete this form", "application form"] },
  public: { example: "The park is open to the public.", translation: "这座公园向公众开放。", exampleForm: "public", collocations: ["the public", "open to the public"] },
  staff: { example: "The hotel staff were friendly and helpful.", translation: "酒店工作人员友好又热心。", exampleForm: "staff", collocations: ["hotel staff", "friendly staff"] },
  front: { example: "The garden is in front of the house.", translation: "花园在房子前面。", exampleForm: "front", collocations: ["in front of", "front of the house"] },
  worry: { example: "Most of the things you worry about never happen.", translation: "你担心的大多数事情其实不会发生。", exampleForm: "worry", collocations: ["worry about", "things you worry about"] },
  plant: { example: "We watered the plant every morning.", translation: "我们每天早上给这株植物浇水。", exampleForm: "plant", collocations: ["water the plant", "the plant"] },
  wide: { example: "This road is wide enough for two buses.", translation: "这条路宽得足以让两辆公交车并行。", exampleForm: "wide", collocations: ["wide enough", "a wide road"] },
  target: { example: "Our sales team reached its monthly target.", translation: "销售团队完成了月度目标。", exampleForm: "target", collocations: ["monthly target", "reach a target"] },
  network: { example: "The office network is down this morning.", translation: "办公室网络今天早上断了。", exampleForm: "network", collocations: ["office network", "network is down"] },
  task: { example: "I must finish the task by tomorrow.", translation: "我必须在明天之前完成任务。", exampleForm: "task", collocations: ["finish the task", "complete a task"] },

  stuff: { meaning: "东西；材料；填充", example: "I packed my stuff before the trip.", translation: "旅行前我收拾好了自己的东西。", exampleForm: "stuff", collocations: ["my stuff", "packed my stuff"] },
  transfer: { example: "I transferred the money this morning.", translation: "我今天早上转了账。", exampleForm: "transferred", collocations: ["transferred the money", "money transfer"] },
  payment: { example: "Can I make the payment by card?", translation: "我可以用银行卡付款吗？", exampleForm: "payment", collocations: ["make the payment", "payment by card"] },
  heat: { example: "Please stay inside during the afternoon heat.", translation: "午后炎热时请待在室内。", exampleForm: "heat", collocations: ["afternoon heat", "during the heat"] },
  pink: { meaning: "粉红色；粉红色的", example: "She wore a pink shirt.", translation: "她穿了一件粉红色衬衫。", exampleForm: "pink", collocations: ["pink shirt", "wore pink"] },
  jacket: { example: "What material is this jacket made of?", translation: "这件夹克是什么材料做的？", exampleForm: "jacket", collocations: ["this jacket", "jacket made of"] },
  behave: { example: "The children behaved well at dinner.", translation: "孩子们吃饭时表现得很好。", exampleForm: "behaved", collocations: ["behaved well", "behave at dinner"] },
  drag: { meaning: "拖；拽；拖动", example: "Drag the file into this folder.", translation: "把文件拖进这个文件夹。", exampleForm: "Drag", collocations: ["drag the file", "drag into"] },
  pump: { meaning: "泵；打气筒；抽送", example: "Use this pump to fill the bicycle tire.", translation: "用这个打气筒给自行车轮胎充气。", exampleForm: "pump", collocations: ["use this pump", "bicycle pump"] },
  tail: { example: "The dog wagged its tail.", translation: "这只狗摇了摇尾巴。", exampleForm: "tail", collocations: ["its tail", "wagged its tail"] },
  intense: { example: "The summer heat is intense today.", translation: "今天暑气很强。", exampleForm: "intense", collocations: ["intense heat", "is intense"] },
  distinct: { example: "These two words have distinct meanings.", translation: "这两个词的含义不同。", exampleForm: "distinct", collocations: ["distinct meanings", "have distinct"] },
  regardless: { meaning: "不顾；不管怎样", example: "We will go regardless of the weather.", translation: "不管天气如何，我们都会去。", exampleForm: "regardless", collocations: ["regardless of", "regardless of the weather"] },
  insure: { meaning: "为……投保；确保", example: "You should insure your car before driving it.", translation: "开车前你应该先给汽车投保。", exampleForm: "insure", collocations: ["insure your car", "fully insured"] },
  ashamed: { example: "You don't need to feel ashamed of making a mistake.", translation: "犯错不必感到羞愧。", exampleForm: "ashamed", collocations: ["feel ashamed", "ashamed of"] },
  portrait: { example: "There is a portrait on the wall.", translation: "墙上挂着一幅肖像画。", exampleForm: "portrait", collocations: ["a portrait", "portrait on the wall"] },
  gaze: { meaning: "凝视；注视", example: "We stopped to gaze at the stars.", translation: "我们停下来凝望星星。", exampleForm: "gaze", collocations: ["gaze at", "gaze at the stars"] },
  grin: { meaning: "露齿笑；咧嘴笑", example: "He gave me a friendly grin.", translation: "他友好地冲我咧嘴一笑。", exampleForm: "grin", collocations: ["friendly grin", "gave a grin"] },
  dollar: { example: "This notebook costs one dollar.", translation: "这本笔记本只要一美元。", exampleForm: "dollar", collocations: ["one dollar", "dollar bill"] },
  host: { example: "Our host welcomed us at the door.", translation: "主人在门口迎接了我们。", exampleForm: "host", collocations: ["our host", "host welcomed us"] },
  wire: { example: "The charger has a loose wire.", translation: "这个充电器有一根电线松了。", exampleForm: "wire", collocations: ["loose wire", "a wire"] },
  equivalent: { example: "One kilometer is equivalent to about 0.62 miles.", translation: "一公里约等于 0.62 英里。", exampleForm: "equivalent", collocations: ["equivalent to", "roughly equivalent"] },
  owe: { example: "I owe my success to my family.", translation: "我的成功要归功于家人。", exampleForm: "owe", collocations: ["owe my success to", "owe it to"] },
  hand: { meaning: "手；帮助；递交", example: "Please raise your hand if you have a question.", translation: "如果你有问题，请举手。", exampleForm: "hand", collocations: ["raise your hand", "give me a hand"] },
  friend: { meaning: "朋友", example: "A good friend listens when you need help.", translation: "好朋友会在你需要帮助时倾听。", exampleForm: "friend", collocations: ["a good friend", "close friend"] },
  learn: { meaning: "学习；得知", example: "I want to learn English this year.", translation: "我今年想学英语。", exampleForm: "learn", collocations: ["learn English", "learn to speak"] },
  doubt: { meaning: "怀疑；疑惑", example: "I doubt that the shop is still open.", translation: "我怀疑那家商店还开着。", exampleForm: "doubt", collocations: ["I doubt that", "without doubt"] },
  crisis: { meaning: "危机；紧要关头", example: "The company needs a clear plan for this crisis.", translation: "公司需要一份应对这场危机的明确方案。", exampleForm: "crisis", collocations: ["this crisis", "economic crisis"] },
  wound: { meaning: "伤口；创伤；使受伤", example: "The nurse cleaned the wound carefully.", translation: "护士仔细清理了伤口。", exampleForm: "wound", collocations: ["clean the wound", "a deep wound"] },
  grammar: { meaning: "语法；语法学", example: "This book explains English grammar clearly.", translation: "这本书把英语语法解释得很清楚。", exampleForm: "grammar", collocations: ["English grammar", "grammar rule"] },
  course: { meaning: "课程；路线；过程；当然（of course）", example: "Of course I accepted his offer of help.", translation: "我当然接受了他的帮助。", exampleForm: "course", collocations: ["of course", "take a course"] },
  set: { meaning: "放置；设定；一套；出发（set out）", example: "She set out on a trip last week.", translation: "她上周出发去旅行了。", exampleForm: "set", collocations: ["set out", "set a time"] },
  turn: { meaning: "转动；转弯；轮到；拒绝（turn down）", example: "The offer is too good to turn down.", translation: "这个提议太好了，让人难以拒绝。", exampleForm: "turn", collocations: ["turn down", "turn left"] },
  hold: { meaning: "拿住；持有；举行；稍等（hold on）", example: "Hold on, someone is knocking at the door.", translation: "等一下，有人在敲门。", exampleForm: "Hold", collocations: ["hold on", "hold a meeting"] },
  true: { meaning: "真实的；真正的；正确的", example: "A true friend will listen to you.", translation: "真正的朋友会倾听你。", exampleForm: "true", collocations: ["a true friend", "come true"] },
  scientist: { example: "The scientist explained the result clearly.", translation: "这位科学家清楚地解释了结果。", exampleForm: "scientist", collocations: ["the scientist", "research scientist"] },
  phone: { meaning: "电话；手机；打电话", example: "I need to charge my phone.", translation: "我需要给手机充电。", exampleForm: "phone", collocations: ["my phone", "charge the phone"] },
  screen: { meaning: "屏幕；银幕；筛选", example: "The text is clear on this screen.", translation: "这个屏幕上的文字很清楚。", exampleForm: "screen", collocations: ["on the screen", "phone screen"] },
  explain: { example: "Could you explain this rule to me?", translation: "你能给我解释一下这条规则吗？", exampleForm: "explain", collocations: ["explain this", "explain to me"] },
  finally: { example: "The bus finally arrived.", translation: "公交车终于到了。", exampleForm: "finally", collocations: ["finally arrived", "finally ready"] },
  trial: { meaning: "审判；试验；考验", example: "The trial will begin next week.", translation: "审判将于下周开始。", exampleForm: "trial", collocations: ["the trial", "begin a trial"] },
  bear: { meaning: "熊；忍受；承受", example: "I can't bear the noise any longer.", translation: "我再也受不了这种噪音了。", exampleForm: "bear", collocations: ["can't bear", "bear the noise"] },
  thin: { meaning: "薄的；瘦的；稀薄的", example: "Cut the bread into thin slices.", translation: "把面包切成薄片。", exampleForm: "thin", collocations: ["thin slices", "a thin layer"] },
  scare: { meaning: "使害怕；惊吓", example: "The sudden noise scared me.", translation: "突然的响声吓了我一跳。", exampleForm: "scared", collocations: ["scared me", "scare someone"] },
  bloody: { meaning: "血腥的；沾血的；该死的（英式粗话）", example: "The word ‘bloody’ can sound rude in British English.", translation: "‘bloody’在英式英语中可能显得粗鲁。", exampleForm: "bloody", collocations: ["bloody difficult", "a bloody mess"] },
  stupid: { example: "It was a stupid mistake, but I learned from it.", translation: "那是个愚蠢的错误，但我从中吸取了教训。", exampleForm: "stupid", collocations: ["stupid mistake", "feel stupid"] },
  destruction: { example: "The storm caused serious destruction along the coast.", translation: "暴风雨对沿海地区造成了严重破坏。", exampleForm: "destruction", collocations: ["serious destruction", "cause destruction"] },
};
